### ISSUE TITLE
Expectation management: How much attention will this repository receive?

### ISSUE THREAD

**Issue by pascalwengerter** [sanity-io/sanity-plugin-media#116]
I've just installed this plugin in my Sanity project and am wondering what the plan is - there's a roadmap of future features, some seemingly low-hanging fruits in terms of bugs and a handful of dependency-bump-PRs that don't get any attention

**Comment by robinpyon** [comment]
Hey @pascalwengerter –

This is an official Sanity plugin and sees a considerable amount of usage – you can expect it to be maintained and working on the latest version of Sanity Studio v3. 

Understandably, we can do a better job of keeping up to date with issues here.

The roadmap is a byproduct of when this still an unofficial / personal project, apologies if this has sent mixed messages – it has since been removed.

**Comment by pascalwengerter** [comment]
@robinpyon thanks for the swift reply! Would you mind also checking asset/file-related issues or feature requests like https://github.com/sanity-io/sanity/issues/3871 in the main repo and move them here, providing official feedback as well?
