### ISSUE TITLE
[Feature Request] - Filtering by multiple tags

### ISSUE THREAD

**Issue by patrickkenyon** [sanity-io/sanity-plugin-media#72]
Unless I'm missing something I believe assets can only be filtered by one tag type. It would be really useful (and we have this use case in the company I work for).

e.g.

`photo_a` | tags: 'animal', 'funny'
`photo_b` | tags: 'animal'
`photo_c` | tags: 'funny'

It should be possible to add two tags to the filter and narrow your results to just `photo_a`

**Comment by Igor178** [comment]
Highly interested in this as well :)

**Comment by dandc11** [comment]
+1 here

**Comment by iandoesallthethings** [comment]
Me too! Is there a technical barrier for this?

**Comment by robinpyon** [comment]
This has been possible in the v2 branch for some time – but only recently landed in the v3 version in [2.1.0](https://github.com/sanity-io/sanity-plugin-media/releases/tag/v2.1.0)!

It's now possible to add duplicate filters and search on multiple tags (or other filters), which should hopefully allow you to accomplish what you're after.

**Comment by MarcelloTheArcane** [comment]
@robinpyon This is good, but it would also be nice to add an "or" filtering option, rather than just "and" - for example

1. "animal", "elephant"
2. "animal", "bear"
3. "animal", "penguin"
4. "plant", "daisy"

There's currently no way of getting just 1 and 2.

Prior art from Airtable:
![image](https://github.com/user-attachments/assets/a932f971-1143-47de-80aa-c4c5789c0f63)

Prior art from Pipedrive:
![image](https://github.com/user-attachments/assets/9a65e243-47a0-4b41-9f5a-f27cc30f5e05)

Should this be a separate issue?
